version: '3.8'

services:
  auth:
    build:
      context: auth/
    depends_on:
      - db-auth
  db-auth:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - /var/lib/postgresql/data
      - ./auth/init.sql:/docker-entrypoint-initdb.d/init.sql
  casa:
    build:
      context: casa/
    depends_on:
      - db-casa
  db-casa:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: casa
    volumes:
      - /var/lib/postgresql/data
      - ./casa/init.sql:/docker-entrypoint-initdb.d/init.sql
  gateway:
    build:
      context: gateway/
    ports:
      - 5001:80
    depends_on:
      - casa
      - auth
